# Generated by Django 4.1.1 on 2022-09-14 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=265, verbose_name='Name')),
                ('last_name', models.CharField(max_length=265, verbose_name='Last name')),
                ('middle_name', models.CharField(default='', max_length=265, verbose_name='Middle name')),
                ('birthday', models.DateField(blank=True, max_length=265, null=True, verbose_name='Birth day')),
                ('photo', models.ImageField(null=True, upload_to='', verbose_name='Photo')),
                ('ticket', models.CharField(max_length=256, verbose_name='Ticket')),
                ('notes', models.TextField(blank=True, verbose_name='Additional notes')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
        ),
    ]
