# Generated by Django 4.1.1 on 2022-09-16 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=265, verbose_name='Middle name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='ticket',
            field=models.CharField(blank=True, max_length=256, verbose_name='Ticket'),
        ),
    ]
